### ISSUE TITLE
`AbsTaskSummarization` using `STSEvaluator` instead of `SummarizationEvalutor`?

### ISSUE THREAD

**Issue by alt-glitch** [yixuantt/FinMTEB#2]
Hey!

While going through your implementation to [add FinMTEB to MTEB](https://github.com/embeddings-benchmark/mteb/pull/1379), I found that the [summarization abstract class](https://github.com/yixuantt/FinMTEB/blob/272ac35888b69c15dab2ba62c890cfa7fcc923a3/finance_mteb/evaluation/evaluators/SummarizationEvaluator.py) uses `STSEvaluator` instead of the `SummarizationEvaluator`

https://github.com/yixuantt/FinMTEB/blob/272ac35888b69c15dab2ba62c890cfa7fcc923a3/finance_mteb/abstasks/AbsTaskSummarization.py#L40-L48

This _seemed_ like a bug so I thought I would let you know.

If this is intended, I'd like to better understand why so!

Thank you!

**Comment by yixuantt** [comment]
Hi, it's not a bug. We do not have a human_summaries/relevance score for the summarization task. Instead, we compare the Spearman correlation based on the semantic similarity between the summary and the text. The semantic meaning of a summary must be highly correlated to the text. 

To simplify, we directly use the STSEvaluator here, which serves the same function.

**Comment by alt-glitch** [comment]
Understood. Thank you for the explanation!
